# Generated by Django 3.0.5 on 2020-04-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_adminProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='priceSell',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nombre del producto', max_length=30),
        ),
    ]
