# Generated by Django 3.0.5 on 2020-04-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_adminProduct', '0002_auto_20200412_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='Hola', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceSell',
            field=models.CharField(blank=True, default='Hola', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='Hola', max_length=20),
        ),
    ]
