# Generated by Django 3.0.5 on 2020-04-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_adminProduct', '0003_auto_20200412_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priceSell',
        ),
        migrations.AddField(
            model_name='product',
            name='priceSale',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
