# Generated by Django 3.0.5 on 2020-04-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_adminProduct', '0004_auto_20200413_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImg',
            field=models.ImageField(default=True, upload_to='images/'),
            preserve_default=False,
        ),
    ]
